repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.3.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
  - repo: https://github.com/golangci/golangci-lint
    rev: v1.44.0
    hooks:
      - id: golangci-lint
